n = str(input('Digite seu nome completo:')).strip()
print('Analisando seu nome...')
#print('Seu nome em maiúsculo é:', n.upper())
print('Seu nome em maiúsculo é {}'.format(n.upper()))
print('Seu nome em minúsculo é {}'.format(n.lower()))
#print('Seu nome em minúsculo é :', n.lower())
p = n.split()
#a = (len(p[0]))
#b = (len(p[1]))
#c = (len(p[2]))
#d = (len(p[3]))
#m = (a + b + c + d)
#print('Seu nome ao total tem', len(n) - n.count(' '), 'letras.')
print('Seu nome ao total tem {} letras.'.format(len(n) - n.count(' ')))
#print('Seu primeiro nome tem {} letras.'.format(n.find(' ')))
print('Seu primeiro nome é', p[0], 'e tem', len(p[0]), 'letras.')
