num = int(input('Digite um número:'))
#num1 = (num - 1)
#num2 = (num + 1)
#print('Analisanto o valor ',num,'Seu antecessor é',num1,'e seu sucessor é',num2)
#print('Analisando o valor {}, seu antecessor é {} e o sucessor é {}'.format(num,num1,num2))
print ('analisando o valor {}, seu antecessor é {} e o sucessor é {}'.format(num, num-1, num+1))